{
    'name': 'Odoo Slack Connector',
    'version': '1.0',
    'summary': 'A Simple Odoo Module that integrates Slack communications with Odoo records.',
    'sequence': -100,
    'description': """Odoo Slack Connector by ProCloud""",
    'category': 'Customizations',
    'website': 'https://www.example.com',
    'depends': ['base'],
    'data': [],
    'demo': [],
    'installable': True,
    'application': True,
    'auto_install': True,
}
